### PR TITLE
Add schemas (schema.org)

### PR DESCRIPTION
**Pull request by smolak**
### What
I will add, step by step, different schemas. I will try to explain what and why I introduced given changes.

### Why?
Because we deserve a good structured data on our blog! :)

### Things to do
- [x] add schemas on blogs list
- [x] add schemas on single blog post
- [x] ... perhaps some more, like menu, footer, etc.
- [x] click through whole blog to see if [removing trailing slash](https://github.com/holidaycheck/tech-blog/pull/83/commits/15c8b0d1e53f41ef4fc42a960fe20638c27c3b10) didn't break anything

### Also
 - some html tags were changed (e.g. `div` -> `article`) or added (e.g. `time`)
 - added favicon (we will now have less 404s because browsers look for that file on each page view)

Consider this a work in progress, as I might not finish this in one day and I might also have some questions (e.g. how to get this data and do something with it).

### CODE REVIEW

**Comment by gilligan** [comment]
Can you explain the purpose of this PR? I don’t understand it. All you do is remove the article schema. What is the benefit of merging this change? Is it somehow better to have no schema at all?

**Comment by smolak** [comment]
I will more commits soon. I wanted to create this PR already as I might stop at certain point if I won’t know how to deal with this template mechanism we use.

**Comment by gilligan** [comment]
Sorry, just didn’t realize that it’s WIP before and wondered why you wanted to merge that one small change 😅

**Comment by wolframkriesing** [comment]
this is cool. what if you remove the WIP and allow us to merge it step by step?
so we get the value of the metadata as soon as another chunk was added!?
would be nice to not have to wait for all of it, the current one does already improve over what we have

**Comment by smolak** [comment]
Work is done, for now. @wolframkriesing suggestion is very valid.
The last thing is clicking through. After first checks, it looks good.

**Pull request merged**
