### PR TITLE
Post one month apprenticeship

### PR DESCRIPTION
**Pull request by ddanielbee**
Please review and proofread.

### CODE REVIEW

**Comment by HeeL** [comment]
You don't have to fork repos from HC, you should have push access here

**Comment by wolframkriesing** [comment]
@HeeL he tried, and i didnt have time to help yet, this was the easiest way fwd, for now. will check

**Comment by HeeL** [comment]
@wolframkriesing I see, its because he was not  a part of developer group. I've added him, it's should be fine now.

**Comment by wolframkriesing** [comment]
Thanks

cu
Wolfram

Am 17.02.2018 21:08 schrieb "Sergii Paryzhskyi" <notifications@github.com>:

**Comment by ddanielbee** [comment]
We can still merge this PR for this post, and then I'll use the main Repo for the next ones, right? If possible, I'd like it if more people check it out and we can merge it today.

**Comment by HeeL** [comment]
@ddanielbee yes, of course, no need to open new PR. Just wait for someone to review it and it can be merged afterwards

**Pull request merged**
