### PR TITLE
New post: On personal development

### PR DESCRIPTION
**Pull request by Arturszott**
- [x] finish post

### CODE REVIEW

**Comment by wolframkriesing** [comment]
@Arturszott this is not done yet, right? the last paragraph is still a comment ... so i am not merging it yet, right?
I will add a todo item in the description, so that is visible, ok?

**Comment by HeeL** [comment]
are you sure you want to use that photo for author profile? ;)
You will also need an author-md-file, btw

**Comment by Arturszott** [comment]
That's why I added [WIP] :)

**Comment by wolframkriesing** [comment]
ok, thx. gotta get used to a PR with state :) ... in this case I would only create a branch but not a PR ... but I understood it now, thx.

**Comment by Arturszott** [comment]
@wolframkriesing @HeeL finished!

**Comment by wolframkriesing** [comment]
I would actually see the excerpt size change as a separate thing, esp. because we can merge quite fast in this repo here, so we should make use of it and split PRs into things that are separate.

**Comment by selaux** [comment]
@Arturszott Cool article and a nice read 👍 .

**Pull request merged**
