### PR TITLE
thoughts on VSM and ToC after #jbhc17

### PR DESCRIPTION
**Pull request by nistude**
@wolframkriesing or anyone else PTAL

### CODE REVIEW

**Comment by wolframkriesing** [comment]
awesome effort. cool @nistude !!!

**Comment by wolframkriesing** [comment]
@nistude 
screen shot 2017-12-14 at 14 36 05

**Comment by wolframkriesing** [comment]
nice, to have a different view ... actually this makes me think that we should add disqus or some type of discussion board to our blog, to allow valuable discussions take place

**Comment by gilligan** [comment]
LGTM!

**Pull request merged**
